before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/phy-api-go-fake-server
    ldflags:
      - -s -w
      - -X github.com/sacloud/phy-api-go/version.Revision={{.ShortCommit}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: 'phy-api-go-fake-server'
release:
  draft: false
changelog:
  skip: false
