// Copyright 2021 The phy-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 専用グローバルネットワーク 一覧
	// (GET /dedicated_subnets/)
	GetDedicatedSubnets(c *gin.Context, params GetDedicatedSubnetsParams)
	// 専用グローバルネットワーク
	// (GET /dedicated_subnets/{dedicated_subnet_id}/)
	GetDedicatedSubnetsDedicatedSubnetId(c *gin.Context, dedicatedSubnetId DedicatedSubnetId, params GetDedicatedSubnetsDedicatedSubnetIdParams)
	// ローカルネットワーク 一覧
	// (GET /private_networks/)
	GetPrivateNetworks(c *gin.Context, params GetPrivateNetworksParams)
	// ローカルネットワーク 詳細
	// (GET /private_networks/{private_network_id}/)
	GetPrivateNetworksPrivateNetworkId(c *gin.Context, privateNetworkId PrivateNetworkId)
	// サーバー一覧
	// (GET /servers/)
	GetServers(c *gin.Context, params GetServersParams)
	// サーバー
	// (GET /servers/{server_id}/)
	GetServersServerId(c *gin.Context, serverId ServerId)
	// インストール可能OS一覧
	// (GET /servers/{server_id}/os_images/)
	GetServersServerIdOsImages(c *gin.Context, serverId ServerId)
	// OSインストールの実行
	// (POST /servers/{server_id}/os_install/)
	PostServersServerIdOsInstall(c *gin.Context, serverId ServerId, params PostServersServerIdOsInstallParams)
	// ポートチャネル状態取得
	// (GET /servers/{server_id}/port_channels/{port_channel_id}/)
	GetServersServerIdPortChannelsPortChannelId(c *gin.Context, serverId ServerId, portChannelId PortChannelId)
	// ポートチャネル ボンディング設定
	// (POST /servers/{server_id}/port_channels/{port_channel_id}/configure_bonding/)
	PostServersServerIdPortChannelsPortChannelIdConfigureBonding(c *gin.Context, serverId ServerId, portChannelId PortChannelId, params PostServersServerIdPortChannelsPortChannelIdConfigureBondingParams)
	// ポート情報取得
	// (GET /servers/{server_id}/ports/{port_id}/)
	GetServersServerIdPortsPortId(c *gin.Context, serverId ServerId, portId PortId)
	// ポート名称設定
	// (PATCH /servers/{server_id}/ports/{port_id}/)
	PatchServersServerIdPortsPortId(c *gin.Context, serverId ServerId, portId PortId, params PatchServersServerIdPortsPortIdParams)
	// ネットワーク接続設定の変更
	// (POST /servers/{server_id}/ports/{port_id}/assign_network/)
	PostServersServerIdPortsPortIdAssignNetwork(c *gin.Context, serverId ServerId, portId PortId, params PostServersServerIdPortsPortIdAssignNetworkParams)
	// ポート有効/無効設定
	// (POST /servers/{server_id}/ports/{port_id}/enable/)
	PostServersServerIdPortsPortIdEnable(c *gin.Context, serverId ServerId, portId PortId, params PostServersServerIdPortsPortIdEnableParams)
	// トラフィックデータ取得
	// (GET /servers/{server_id}/ports/{port_id}/traffic_graph/)
	GetServersServerIdPortsPortIdTrafficGraph(c *gin.Context, serverId ServerId, portId PortId, params GetServersServerIdPortsPortIdTrafficGraphParams)
	// サーバーの電源操作
	// (POST /servers/{server_id}/power_control/)
	PostServersServerIdPowerControl(c *gin.Context, serverId ServerId, params PostServersServerIdPowerControlParams)
	// サーバーの電源情報を取得する
	// (GET /servers/{server_id}/power_status/)
	GetServersServerIdPowerStatus(c *gin.Context, serverId ServerId)
	// サーバーのRAID状態を取得
	// (GET /servers/{server_id}/raid_status/)
	GetServersServerIdRaidStatus(c *gin.Context, serverId ServerId, params GetServersServerIdRaidStatusParams)
	// サービス一覧
	// (GET /services/)
	GetServices(c *gin.Context, params GetServicesParams)
	// サービス 詳細
	// (GET /services/{service_id}/)
	GetServicesServiceId(c *gin.Context, serviceId ServiceId)
	// サービスの名称・説明の変更
	// (PATCH /services/{service_id}/)
	PatchServicesServiceId(c *gin.Context, serviceId ServiceId, params PatchServicesServiceIdParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(c *gin.Context)

// GetDedicatedSubnets operation middleware
func (siw *ServerInterfaceWrapper) GetDedicatedSubnets(c *gin.Context) {

	var err error

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDedicatedSubnetsParams

	// ------------- Optional query parameter "tag" -------------
	if paramValue := c.Query("tag"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter tag: %s", err)})
		return
	}

	// ------------- Optional query parameter "free_word" -------------
	if paramValue := c.Query("free_word"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "free_word", c.Request.URL.Query(), &params.FreeWord)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter free_word: %s", err)})
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter limit: %s", err)})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter offset: %s", err)})
		return
	}

	// ------------- Optional query parameter "ordering" -------------
	if paramValue := c.Query("ordering"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "ordering", c.Request.URL.Query(), &params.Ordering)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter ordering: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDedicatedSubnets(c, params)
}

// GetDedicatedSubnetsDedicatedSubnetId operation middleware
func (siw *ServerInterfaceWrapper) GetDedicatedSubnetsDedicatedSubnetId(c *gin.Context) {

	var err error

	// ------------- Path parameter "dedicated_subnet_id" -------------
	var dedicatedSubnetId DedicatedSubnetId

	err = runtime.BindStyledParameter("simple", false, "dedicated_subnet_id", c.Param("dedicated_subnet_id"), &dedicatedSubnetId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter dedicated_subnet_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDedicatedSubnetsDedicatedSubnetIdParams

	// ------------- Optional query parameter "refresh" -------------
	if paramValue := c.Query("refresh"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "refresh", c.Request.URL.Query(), &params.Refresh)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter refresh: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDedicatedSubnetsDedicatedSubnetId(c, dedicatedSubnetId, params)
}

// GetPrivateNetworks operation middleware
func (siw *ServerInterfaceWrapper) GetPrivateNetworks(c *gin.Context) {

	var err error

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPrivateNetworksParams

	// ------------- Optional query parameter "tag" -------------
	if paramValue := c.Query("tag"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter tag: %s", err)})
		return
	}

	// ------------- Optional query parameter "free_word" -------------
	if paramValue := c.Query("free_word"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "free_word", c.Request.URL.Query(), &params.FreeWord)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter free_word: %s", err)})
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter limit: %s", err)})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter offset: %s", err)})
		return
	}

	// ------------- Optional query parameter "ordering" -------------
	if paramValue := c.Query("ordering"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "ordering", c.Request.URL.Query(), &params.Ordering)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter ordering: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetPrivateNetworks(c, params)
}

// GetPrivateNetworksPrivateNetworkId operation middleware
func (siw *ServerInterfaceWrapper) GetPrivateNetworksPrivateNetworkId(c *gin.Context) {

	var err error

	// ------------- Path parameter "private_network_id" -------------
	var privateNetworkId PrivateNetworkId

	err = runtime.BindStyledParameter("simple", false, "private_network_id", c.Param("private_network_id"), &privateNetworkId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter private_network_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetPrivateNetworksPrivateNetworkId(c, privateNetworkId)
}

// GetServers operation middleware
func (siw *ServerInterfaceWrapper) GetServers(c *gin.Context) {

	var err error

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServersParams

	// ------------- Optional query parameter "power_status" -------------
	if paramValue := c.Query("power_status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "power_status", c.Request.URL.Query(), &params.PowerStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter power_status: %s", err)})
		return
	}

	// ------------- Optional query parameter "internet" -------------
	if paramValue := c.Query("internet"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "internet", c.Request.URL.Query(), &params.Internet)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter internet: %s", err)})
		return
	}

	// ------------- Optional query parameter "private_network" -------------
	if paramValue := c.Query("private_network"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "private_network", c.Request.URL.Query(), &params.PrivateNetwork)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter private_network: %s", err)})
		return
	}

	// ------------- Optional query parameter "tag" -------------
	if paramValue := c.Query("tag"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter tag: %s", err)})
		return
	}

	// ------------- Optional query parameter "free_word" -------------
	if paramValue := c.Query("free_word"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "free_word", c.Request.URL.Query(), &params.FreeWord)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter free_word: %s", err)})
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter limit: %s", err)})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter offset: %s", err)})
		return
	}

	// ------------- Optional query parameter "ordering" -------------
	if paramValue := c.Query("ordering"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "ordering", c.Request.URL.Query(), &params.Ordering)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter ordering: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServers(c, params)
}

// GetServersServerId operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerId(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerId(c, serverId)
}

// GetServersServerIdOsImages operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdOsImages(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdOsImages(c, serverId)
}

// PostServersServerIdOsInstall operation middleware
func (siw *ServerInterfaceWrapper) PostServersServerIdOsInstall(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServersServerIdOsInstallParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostServersServerIdOsInstallParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostServersServerIdOsInstall(c, serverId, params)
}

// GetServersServerIdPortChannelsPortChannelId operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdPortChannelsPortChannelId(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_channel_id" -------------
	var portChannelId PortChannelId

	err = runtime.BindStyledParameter("simple", false, "port_channel_id", c.Param("port_channel_id"), &portChannelId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_channel_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdPortChannelsPortChannelId(c, serverId, portChannelId)
}

// PostServersServerIdPortChannelsPortChannelIdConfigureBonding operation middleware
func (siw *ServerInterfaceWrapper) PostServersServerIdPortChannelsPortChannelIdConfigureBonding(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_channel_id" -------------
	var portChannelId PortChannelId

	err = runtime.BindStyledParameter("simple", false, "port_channel_id", c.Param("port_channel_id"), &portChannelId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_channel_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServersServerIdPortChannelsPortChannelIdConfigureBondingParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostServersServerIdPortChannelsPortChannelIdConfigureBondingParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostServersServerIdPortChannelsPortChannelIdConfigureBonding(c, serverId, portChannelId, params)
}

// GetServersServerIdPortsPortId operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdPortsPortId(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_id" -------------
	var portId PortId

	err = runtime.BindStyledParameter("simple", false, "port_id", c.Param("port_id"), &portId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdPortsPortId(c, serverId, portId)
}

// PatchServersServerIdPortsPortId operation middleware
func (siw *ServerInterfaceWrapper) PatchServersServerIdPortsPortId(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_id" -------------
	var portId PortId

	err = runtime.BindStyledParameter("simple", false, "port_id", c.Param("port_id"), &portId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchServersServerIdPortsPortIdParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PatchServersServerIdPortsPortIdParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PatchServersServerIdPortsPortId(c, serverId, portId, params)
}

// PostServersServerIdPortsPortIdAssignNetwork operation middleware
func (siw *ServerInterfaceWrapper) PostServersServerIdPortsPortIdAssignNetwork(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_id" -------------
	var portId PortId

	err = runtime.BindStyledParameter("simple", false, "port_id", c.Param("port_id"), &portId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServersServerIdPortsPortIdAssignNetworkParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostServersServerIdPortsPortIdAssignNetworkParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostServersServerIdPortsPortIdAssignNetwork(c, serverId, portId, params)
}

// PostServersServerIdPortsPortIdEnable operation middleware
func (siw *ServerInterfaceWrapper) PostServersServerIdPortsPortIdEnable(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_id" -------------
	var portId PortId

	err = runtime.BindStyledParameter("simple", false, "port_id", c.Param("port_id"), &portId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServersServerIdPortsPortIdEnableParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostServersServerIdPortsPortIdEnableParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostServersServerIdPortsPortIdEnable(c, serverId, portId, params)
}

// GetServersServerIdPortsPortIdTrafficGraph operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdPortsPortIdTrafficGraph(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	// ------------- Path parameter "port_id" -------------
	var portId PortId

	err = runtime.BindStyledParameter("simple", false, "port_id", c.Param("port_id"), &portId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter port_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServersServerIdPortsPortIdTrafficGraphParams

	// ------------- Optional query parameter "since" -------------
	if paramValue := c.Query("since"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "since", c.Request.URL.Query(), &params.Since)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter since: %s", err)})
		return
	}

	// ------------- Optional query parameter "until" -------------
	if paramValue := c.Query("until"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "until", c.Request.URL.Query(), &params.Until)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter until: %s", err)})
		return
	}

	// ------------- Optional query parameter "step" -------------
	if paramValue := c.Query("step"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "step", c.Request.URL.Query(), &params.Step)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter step: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdPortsPortIdTrafficGraph(c, serverId, portId, params)
}

// PostServersServerIdPowerControl operation middleware
func (siw *ServerInterfaceWrapper) PostServersServerIdPowerControl(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServersServerIdPowerControlParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostServersServerIdPowerControlParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostServersServerIdPowerControl(c, serverId, params)
}

// GetServersServerIdPowerStatus operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdPowerStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdPowerStatus(c, serverId)
}

// GetServersServerIdRaidStatus operation middleware
func (siw *ServerInterfaceWrapper) GetServersServerIdRaidStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId ServerId

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter server_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServersServerIdRaidStatusParams

	// ------------- Optional query parameter "refresh" -------------
	if paramValue := c.Query("refresh"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "refresh", c.Request.URL.Query(), &params.Refresh)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter refresh: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServersServerIdRaidStatus(c, serverId, params)
}

// GetServices operation middleware
func (siw *ServerInterfaceWrapper) GetServices(c *gin.Context) {

	var err error

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams

	// ------------- Optional query parameter "product_category" -------------
	if paramValue := c.Query("product_category"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "product_category", c.Request.URL.Query(), &params.ProductCategory)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter product_category: %s", err)})
		return
	}

	// ------------- Optional query parameter "tag" -------------
	if paramValue := c.Query("tag"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter tag: %s", err)})
		return
	}

	// ------------- Optional query parameter "free_word" -------------
	if paramValue := c.Query("free_word"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "free_word", c.Request.URL.Query(), &params.FreeWord)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter free_word: %s", err)})
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter limit: %s", err)})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter offset: %s", err)})
		return
	}

	// ------------- Optional query parameter "ordering" -------------
	if paramValue := c.Query("ordering"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "ordering", c.Request.URL.Query(), &params.Ordering)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter ordering: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServices(c, params)
}

// GetServicesServiceId operation middleware
func (siw *ServerInterfaceWrapper) GetServicesServiceId(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_id" -------------
	var serviceId ServiceId

	err = runtime.BindStyledParameter("simple", false, "service_id", c.Param("service_id"), &serviceId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter service_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetServicesServiceId(c, serviceId)
}

// PatchServicesServiceId operation middleware
func (siw *ServerInterfaceWrapper) PatchServicesServiceId(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_id" -------------
	var serviceId ServiceId

	err = runtime.BindStyledParameter("simple", false, "service_id", c.Param("service_id"), &serviceId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter service_id: %s", err)})
		return
	}

	c.Set(Account_api_keyScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchServicesServiceIdParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PatchServicesServiceIdParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for X-Requested-With, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Requested-With", runtime.ParamLocationHeader, valueList[0], &XRequestedWith)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter X-Requested-With: %s", err)})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Header parameter X-Requested-With is required, but not found: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PatchServicesServiceId(c, serviceId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	router.GET(options.BaseURL+"/dedicated_subnets/", wrapper.GetDedicatedSubnets)

	router.GET(options.BaseURL+"/dedicated_subnets/:dedicated_subnet_id/", wrapper.GetDedicatedSubnetsDedicatedSubnetId)

	router.GET(options.BaseURL+"/private_networks/", wrapper.GetPrivateNetworks)

	router.GET(options.BaseURL+"/private_networks/:private_network_id/", wrapper.GetPrivateNetworksPrivateNetworkId)

	router.GET(options.BaseURL+"/servers/", wrapper.GetServers)

	router.GET(options.BaseURL+"/servers/:server_id/", wrapper.GetServersServerId)

	router.GET(options.BaseURL+"/servers/:server_id/os_images/", wrapper.GetServersServerIdOsImages)

	router.POST(options.BaseURL+"/servers/:server_id/os_install/", wrapper.PostServersServerIdOsInstall)

	router.GET(options.BaseURL+"/servers/:server_id/port_channels/:port_channel_id/", wrapper.GetServersServerIdPortChannelsPortChannelId)

	router.POST(options.BaseURL+"/servers/:server_id/port_channels/:port_channel_id/configure_bonding/", wrapper.PostServersServerIdPortChannelsPortChannelIdConfigureBonding)

	router.GET(options.BaseURL+"/servers/:server_id/ports/:port_id/", wrapper.GetServersServerIdPortsPortId)

	router.PATCH(options.BaseURL+"/servers/:server_id/ports/:port_id/", wrapper.PatchServersServerIdPortsPortId)

	router.POST(options.BaseURL+"/servers/:server_id/ports/:port_id/assign_network/", wrapper.PostServersServerIdPortsPortIdAssignNetwork)

	router.POST(options.BaseURL+"/servers/:server_id/ports/:port_id/enable/", wrapper.PostServersServerIdPortsPortIdEnable)

	router.GET(options.BaseURL+"/servers/:server_id/ports/:port_id/traffic_graph/", wrapper.GetServersServerIdPortsPortIdTrafficGraph)

	router.POST(options.BaseURL+"/servers/:server_id/power_control/", wrapper.PostServersServerIdPowerControl)

	router.GET(options.BaseURL+"/servers/:server_id/power_status/", wrapper.GetServersServerIdPowerStatus)

	router.GET(options.BaseURL+"/servers/:server_id/raid_status/", wrapper.GetServersServerIdRaidStatus)

	router.GET(options.BaseURL+"/services/", wrapper.GetServices)

	router.GET(options.BaseURL+"/services/:service_id/", wrapper.GetServicesServiceId)

	router.PATCH(options.BaseURL+"/services/:service_id/", wrapper.PatchServicesServiceId)

	return router
}
